import { createInterface } from 'readline';
import bcrypt from 'bcrypt';
import { randomBytes } from 'crypto';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = join(__dirname, '..', '.env');

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n=== Claude Phone Hub - Password Setup ===\n');

  const password = await question('Enter your password: ');

  if (password.length < 6) {
    console.error('Password must be at least 6 characters long');
    process.exit(1);
  }

  const confirm = await question('Confirm password: ');

  if (password !== confirm) {
    console.error('Passwords do not match');
    process.exit(1);
  }

  console.log('\nGenerating password hash...');
  const hash = await bcrypt.hash(password, 12);
  const jwtSecret = randomBytes(32).toString('hex');

  let envContent = '';

  if (existsSync(envPath)) {
    envContent = readFileSync(envPath, 'utf-8');
    // Update existing values
    if (envContent.includes('PASSWORD_HASH=')) {
      envContent = envContent.replace(/PASSWORD_HASH=.*/, `PASSWORD_HASH=${hash}`);
    } else {
      envContent += `\nPASSWORD_HASH=${hash}`;
    }
    if (envContent.includes('JWT_SECRET=')) {
      envContent = envContent.replace(/JWT_SECRET=.*/, `JWT_SECRET=${jwtSecret}`);
    } else {
      envContent += `\nJWT_SECRET=${jwtSecret}`;
    }
  } else {
    envContent = `# Claude Phone Hub Configuration
PORT=3000

# Authentication (generated by setup script)
PASSWORD_HASH=${hash}
JWT_SECRET=${jwtSecret}

# Optional: Default working directory for new terminals
DEFAULT_CWD=
`;
  }

  writeFileSync(envPath, envContent);

  console.log('\n.env file has been created/updated with your password hash.');
  console.log('You can now start the server with: npm run dev\n');

  rl.close();
}

main().catch(console.error);
